DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS INFLUENCERS;
DROP TABLE IF EXISTS SPONSORS;
DROP TABLE IF EXISTS ADREQS;
DROP TABLE IF EXISTS CAMPAIGNS;

CREATE TABLE ACCOUNTS (
  username TEXT PRIMARY KEY ,
  password TEXT NOT NULL,
  TYPE TEXT,
  INAPPROPIATE INT DEFAULT 0
);

CREATE TABLE INFLUENCERS (
  USERNAME TEXT PRIMARY KEY,
  NAME TEXT ,
  CATEGORY TEXT,
  NICHE TEXT,
  REACH INT
);

CREATE TABLE SPONSORS (
  NAME TEXT PRIMARY KEY,
  INDUSTRY TEXT,
  BUDGET INT
);

CREATE TABLE ADREQS (
  CAMPAIGN_ID INT ,
  INFLUENCER_ID TEXT,
  MESSAGES TEXT,
  PAYMENT_AMOUNT INT,
  STATUS TEXT
);

CREATE TABLE CAMPAIGNS (
  ID INT AUTO_INCREMENT PRIMARY KEY DEFAULT 0,
  SPONSOR TEXT,
  NAME TEXT,
  DESCRIPTION TEXT,
  PROGRESS TEXT,
  BUDGET INT,
  VISIBILITY TEXT,
  GOALS TEXT,
  INAPPROPIATE INT DEFAULT 0
);
